# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c3f1baf73cd0914e3dcc03c3571002fa3a5fc51170cf34da5f2008bdc2402608bb58d33b37c95e0eb4097e9c11bb8f496f126d628401dba1698318c61d29ee

test:
  secret_key_base: 0c23ed6c3392a3eff6f4647293b83d66b31c2ada3415c3c0d876f251e5703a937ba2197ad03669f2417988c33e8807b66ab744eabd04e0263f23b3e119f8d8e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
